name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup-xentom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          - latest
          - canary
          - '0.0.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xentom CLI
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run Xentom CLI
        run: |
          xentom --version
